# Generated by Django 5.0.3 on 2024-03-26 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_seller'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('product', 'order')},
        ),
    ]
