# Generated by Django 5.0.4 on 2024-04-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_orderitem_unique_together_product_author_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('product', 'order')},
        ),
    ]
