# Generated by Django 5.0.4 on 2024-04-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='ratings_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
